create table scoreboard (id integer, nick varchar(20), score unsigned big int);
insert into scoreboard(nick, score) values ("hoky", 231);
insert into scoreboard(nick, score) values ("llorilin", 1024);
insert into scoreboard(nick, score) values ("infobyte", 18);
insert into scoreboard(nick, score) values ("core", 323);
insert into scoreboard(nick, score) values ("delloite", 239);
insert into scoreboard(nick, score) values ("pasta", 543);
insert into scoreboard(nick, score) values ("ordenados en el caos", 90);
insert into scoreboard(nick, score) values ("prueba", 450);
insert into scoreboard(nick, score) values ("martin", 23);
insert into scoreboard(nick, score) values ("tarta", 239);
insert into scoreboard(nick, score) values ("juanito", 45);
insert into scoreboard(nick, score) values ("fercato", 12);
insert into scoreboard(nick, score) values ("shei", 8);
insert into scoreboard(nick, score) values ("joaco", 237);
insert into scoreboard(nick, score) values ("eze", 9);
insert into scoreboard(nick, score) values ("caraciulo", 904);
insert into scoreboard(nick, score) values ("hax0r", 776);
insert into scoreboard(nick, score) values ("panchi", 34);
insert into scoreboard(nick, score) values ("panci", 35);
insert into scoreboard(nick, score) values ("napo", 12329);
insert into scoreboard(nick, score) values ("nox", 9823);
insert into scoreboard(nick, score) values ("ricnar", 459);
insert into scoreboard(nick, score) values ("chema", 2);
insert into scoreboard(nick, score) values ("ionescu", 84);
